-- Dev migration. Hibernate 6 mappings: enum columns are ENUM and LocalDateTime columns DATETIME(6).
ALTER TABLE events MODIFY type ENUM('PHOTO_BINGO','PHOTO_EXHIBITION') NOT NULL;
ALTER TABLE announcements MODIFY type ENUM('MANUAL','BIRTHDAY','EVENT') NOT NULL;
ALTER TABLE announcements ADD COLUMN related_event_url VARCHAR(300) NULL;
ALTER TABLE announcements ADD COLUMN related_label VARCHAR(80) NULL, ADD COLUMN expires_at DATETIME(6) NULL;
ALTER TABLE posts ADD COLUMN photo_exhibition_submission_id BIGINT NULL, ADD UNIQUE KEY idx_posts_photo_exhibition_submission (photo_exhibition_submission_id);
ALTER TABLE posts ADD COLUMN photo_exhibition_event_id BIGINT NULL, ADD KEY idx_posts_photo_exhibition_event (photo_exhibition_event_id);
CREATE TABLE photo_exhibition_configs (id BIGINT NOT NULL AUTO_INCREMENT,event_id BIGINT NOT NULL,submission_start DATETIME(6) NOT NULL,submission_end DATETIME(6) NOT NULL,review_end DATETIME(6) NOT NULL,voting_end DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_exhibition_config_event(event_id),CONSTRAINT fk_exhibition_config_event FOREIGN KEY (event_id) REFERENCES events(id));
CREATE TABLE photo_exhibition_submissions (id BIGINT NOT NULL AUTO_INCREMENT,event_id BIGINT NOT NULL,user_id BIGINT NOT NULL,title VARCHAR(150) NOT NULL,introduction TEXT NULL,excluded BIT NOT NULL,exclusion_reason VARCHAR(500) NULL,final_votes INT NOT NULL,result_tier VARCHAR(20) NULL,plaza_post_id BIGINT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_photo_exhibition_event_user(event_id,user_id),KEY idx_exhibition_submission_event (event_id),CONSTRAINT fk_exhibition_submission_event FOREIGN KEY (event_id) REFERENCES events(id),CONSTRAINT fk_exhibition_submission_user FOREIGN KEY (user_id) REFERENCES users(id));
CREATE TABLE photo_exhibition_images (id BIGINT NOT NULL AUTO_INCREMENT,submission_id BIGINT NOT NULL,image_url VARCHAR(500) NOT NULL,sort_order INT NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_exhibition_image_order(submission_id,sort_order),CONSTRAINT fk_exhibition_images_submission FOREIGN KEY (submission_id) REFERENCES photo_exhibition_submissions(id) ON DELETE CASCADE);
CREATE TABLE photo_exhibition_votes (id BIGINT NOT NULL AUTO_INCREMENT,event_id BIGINT NOT NULL,voter_id BIGINT NOT NULL,submission_id BIGINT NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_exhibition_voter_work(event_id,voter_id,submission_id),KEY idx_exhibition_vote_event (event_id),KEY idx_exhibition_vote_submission (submission_id),KEY idx_exhibition_vote_voter (voter_id),CONSTRAINT fk_exhibition_vote_event FOREIGN KEY (event_id) REFERENCES events(id),CONSTRAINT fk_exhibition_vote_voter FOREIGN KEY (voter_id) REFERENCES users(id),CONSTRAINT fk_exhibition_vote_submission FOREIGN KEY (submission_id) REFERENCES photo_exhibition_submissions(id));
CREATE TABLE photo_exhibition_reward_grants (id BIGINT NOT NULL AUTO_INCREMENT,event_id BIGINT NOT NULL,user_id BIGINT NOT NULL,grant_kind VARCHAR(30) NOT NULL,amount INT NOT NULL,created_at DATETIME(6) NOT NULL,PRIMARY KEY(id),UNIQUE KEY uk_exhibition_reward_once(event_id,user_id,grant_kind),KEY idx_exhibition_grant_event (event_id),KEY idx_exhibition_grant_user (user_id),CONSTRAINT fk_exhibition_grant_event FOREIGN KEY (event_id) REFERENCES events(id),CONSTRAINT fk_exhibition_grant_user FOREIGN KEY (user_id) REFERENCES users(id));
